# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='closed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='opened',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opened', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
